version: '3'
services:
  executor-go:
    container_name: ohmycode-executor-go
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./requests:/app/requests
      - ./results:/app/results
