version: '3'
services:
  executor-php82:
    container_name: ohmycode-executor-php82
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./requests:/app/requests
      - ./results:/app/results
