version: '3.8'
services:
  executor-manager:
    container_name: ohmycode-executor-manager
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./php82:/app/php82
      - ./mysql8:/app/mysql8
      - ./go:/app/go
  executor-php82:
    container_name: ohmycode-executor-php82
    build:
      context: ./php82
      dockerfile: Dockerfile
    volumes:
      - ./php82/requests:/app/requests
      - ./php82/results:/app/results
  executor-mysql8:
    container_name: ohmycode-executor-mysql8
    build:
      context: ./mysql8
      dockerfile: Dockerfile
    volumes:
      - ./mysql8/requests:/app/requests
      - ./mysql8/results:/app/results
    command: --default-authentication-plugin=mysql_native_password --skip-log-bin
  executor-go:
    container_name: ohmycode-executor-go
    build:
      context: ./go
      dockerfile: Dockerfile
    volumes:
      - ./go/requests:/app/requests
      - ./go/results:/app/results
