version: '3.8'
services:
  runner-manager:
    container_name: ohmycode-runner-manager
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./php82:/app/php82
      - ./mysql8:/app/mysql8
      - ./postgres13:/app/postgres13
      - ./go:/app/go
      - ./java:/app/java
  runner-postgres13:
    container_name: ohmycode-runner-postgres13
    image: postgres:13
    restart: always
    volumes:
      - ./postgres13/requests:/app/requests
      - ./postgres13/results:/app/results
      - ./postgres13/runner.sh:/docker-entrypoint-initdb.d/runner.sh
    tmpfs:
      - /var/lib/postgresql/data:exec,mode=1777
      - /app/tmp:exec,mode=1777
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
  runner-php82:
    container_name: ohmycode-runner-php82
    build:
      context: ./php82
      dockerfile: Dockerfile
    volumes:
      - ./php82/requests:/app/requests
      - ./php82/results:/app/results
  runner-mysql8:
    container_name: ohmycode-runner-mysql8
    build:
      context: ./mysql8
      dockerfile: Dockerfile
    volumes:
      - ./mysql8/requests:/app/requests
      - ./mysql8/results:/app/results
    tmpfs:
      - /var/lib/mysql:exec,mode=1777
    command: --mysql-native-password=ON --log_error_verbosity=1 --skip-log-bin
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  runner-go:
    container_name: ohmycode-runner-go
    build:
      context: ./go
      dockerfile: Dockerfile
    volumes:
      - ./go/requests:/app/requests
      - ./go/results:/app/results
  runner-java:
    container_name: ohmycode-runner-java
    build:
      context: ./java
      dockerfile: Dockerfile
    volumes:
      - ./java/requests:/app/requests
      - ./java/results:/app/results

# docker-compose up --build --remove-orphans --force-recreate