version: '3.8'
services:
  runner-manager:
    container_name: ohmycode-runner-manager
    build:
      context: .
      dockerfile: Dockerfile
    stop_grace_period: 1s
    restart: always
    volumes:
      - ./php82:/app/php82
      - ./mysql8:/app/mysql8
      - ./postgres13:/app/postgres13
      - ./go:/app/go
      - ./java:/app/java
  runner-postgres13:
    container_name: ohmycode-runner-postgres13
    build:
      context: ./postgres13
      dockerfile: Dockerfile
    cap_add:
      - SYS_NICE
    stop_grace_period: 1s
    restart: always
    volumes:
      - ./postgres13/requests:/app/requests
      - ./postgres13/results:/app/results
      - ./postgres13/runner.sh:/docker-entrypoint-initdb.d/runner.sh
    tmpfs:
      - /var/lib/postgresql/data:mode=1777,uid=1000,gid=1000
      - /app/tmp:mode=1777,uid=1000,gid=1000
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
  runner-php82:
    container_name: ohmycode-runner-php82
    build:
      context: ./php82
      dockerfile: Dockerfile
    stop_grace_period: 1s
    restart: always
    volumes:
      - ./php82/requests:/app/requests
      - ./php82/results:/app/results
    tmpfs:
      - /app/tmp:mode=1777,uid=1000,gid=1000
  runner-mysql8:
    container_name: ohmycode-runner-mysql8
    build:
      context: ./mysql8
      dockerfile: Dockerfile
    cap_add:
      - SYS_NICE
    stop_grace_period: 1s
    restart: always
    volumes:
      - ./mysql8/requests:/app/requests
      - ./mysql8/results:/app/results
      - ./mysql8/runner.sh:/docker-entrypoint-initdb.d/runner.sh
    tmpfs:
      - /var/lib/mysql:mode=1777,uid=1000,gid=1000
      - /app/tmp:mode=1777,uid=1000,gid=1000
    command: --default-authentication-plugin=mysql_native_password --log_error_verbosity=1 --skip-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: mysql8root
  runner-go:
    container_name: ohmycode-runner-go
    build:
      context: ./go
      dockerfile: Dockerfile
    stop_grace_period: 1s
    restart: always
    volumes:
      - ./go/requests:/app/requests
      - ./go/results:/app/results
    tmpfs:
      - /app/go:mode=1777,uid=1000,gid=1000
      - /app/tmp:mode=1777,uid=1000,gid=1000
  runner-java:
    container_name: ohmycode-runner-java
    build:
      context: ./java
      dockerfile: Dockerfile
    stop_grace_period: 1s
    restart: always
    volumes:
      - ./java/requests:/app/requests
      - ./java/results:/app/results
    tmpfs:
      - /app/java:mode=1777,uid=1000,gid=1000
      - /app/tmp:mode=1777,uid=1000,gid=1000

# docker-compose up --build --remove-orphans --force-recreate