name: "ohmycode-client"
services:
  ohmycode-client-nginx:
    container_name: ohmycode-client-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../public:/usr/share/nginx/public
    command: /bin/bash -c "cp -n /usr/share/nginx/public/js/conf-example.js /usr/share/nginx/public/js/conf.js & echo 'OhMyCode-client started' & nginx -g 'daemon off;'"
    ports:
      - "52673:8080"