version: '3'
services:
  mysql:
    container_name: ohmycode-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ohmycode
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    command: --default-authentication-plugin=mysql_native_password --log_error_verbosity=1 --skip-log-bin
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "33713:3306"
    networks:
      - ohmycode-network
  php:
    container_name: ohmycode-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_CLI_SERVER_WORKERS: 20
    ports:
      - "8080:80"
    volumes:
      - ./public:/api/public
      - ./app:/api/app
      - ./api-conf.json:/api/api-conf.json
    depends_on:
      - mysql
    networks:
      - ohmycode-network
networks:
  ohmycode-network:
    driver: bridge
